<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        $settings = [
            // Home Page (Extra Sections)
            [
                'key' => 'home_events_title',
                'display_name' => 'Home Events Section Title',
                'value' => 'Upcoming Events',
                'type' => 'text',
                'group' => 'Home Page',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'home_events_subtitle',
                'display_name' => 'Home Events Section Subtitle',
                'value' => 'Join our upcoming historical tours and webinars.',
                'type' => 'textarea',
                'group' => 'Home Page',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'home_events_view_all_text',
                'display_name' => 'Home Events View All Button Text',
                'value' => 'View All Events',
                'type' => 'text',
                'group' => 'Home Page',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'home_events_register_text',
                'display_name' => 'Home Events Register Button Text',
                'value' => 'Register',
                'type' => 'text',
                'group' => 'Home Page',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'home_library_title',
                'display_name' => 'Home Library Section Title',
                'value' => 'E-Book Showcase',
                'type' => 'text',
                'group' => 'Home Page',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'home_library_subtitle',
                'display_name' => 'Home Library Section Subtitle',
                'value' => 'Explore our curated digital library of Indonesian history. Exclusive publications available for members.',
                'type' => 'textarea',
                'group' => 'Home Page',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'home_library_explore_text',
                'display_name' => 'Home Library Explore Button Text',
                'value' => 'Explore E-Library',
                'type' => 'text',
                'group' => 'Home Page',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'home_library_read_sample_text',
                'display_name' => 'Home Library Read Sample Link Text',
                'value' => 'Read Sample',
                'type' => 'text',
                'group' => 'Home Page',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'home_library_get_ebook_text',
                'display_name' => 'Home Library Get Ebook Link Text',
                'value' => 'Get E-Book',
                'type' => 'text',
                'group' => 'Home Page',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'home_merchandise_title',
                'display_name' => 'Home Merchandise Section Title',
                'value' => 'Merchandise Catalog',
                'type' => 'text',
                'group' => 'Home Page',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'home_merchandise_subtitle',
                'display_name' => 'Home Merchandise Section Subtitle',
                'value' => 'Support our mission by wearing history.',
                'type' => 'textarea',
                'group' => 'Home Page',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'home_merchandise_view_all_text',
                'display_name' => 'Home Merchandise View All Button Text',
                'value' => 'View All Shop',
                'type' => 'text',
                'group' => 'Home Page',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'home_merchandise_view_product_text',
                'display_name' => 'Home Merchandise View Product Button Text',
                'value' => 'View Product',
                'type' => 'text',
                'group' => 'Home Page',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'home_news_title',
                'display_name' => 'Home News Section Title',
                'value' => 'Historia News',
                'type' => 'text',
                'group' => 'Home Page',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'home_news_subtitle',
                'display_name' => 'Home News Section Subtitle',
                'value' => 'Check out some of our latest blog posts below.',
                'type' => 'textarea',
                'group' => 'Home Page',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'home_news_view_all_text',
                'display_name' => 'Home News View All Button Text',
                'value' => 'Lihat selengkapnya',
                'type' => 'text',
                'group' => 'Home Page',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'home_news_read_more_text',
                'display_name' => 'Home News Read More Link Text',
                'value' => 'Read More',
                'type' => 'text',
                'group' => 'Home Page',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'home_recognition_title',
                'display_name' => 'Home Recognition Section Title',
                'value' => 'Prestasi & Penghargaan',
                'type' => 'text',
                'group' => 'Home Page',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'home_recognition_subtitle',
                'display_name' => 'Home Recognition Section Subtitle',
                'value' => 'Dedikasi kami dalam melestarikan sejarah telah diakui oleh berbagai institusi.',
                'type' => 'textarea',
                'group' => 'Home Page',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'home_cta_title',
                'display_name' => 'Home CTA Section Title',
                'value' => 'Gabung Bersama KHI',
                'type' => 'text',
                'group' => 'Home Page',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'home_cta_subtitle',
                'display_name' => 'Home CTA Section Subtitle',
                'value' => 'Jadilah bagian dari penjaga memori bangsa. Nikmati akses eksklusif ke arsip digital, prioritas pendaftaran acara, dan jaringan komunitas sejarah terbesar di Indonesia.',
                'type' => 'textarea',
                'group' => 'Home Page',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'home_cta_primary_btn_text',
                'display_name' => 'Home CTA Primary Button Text',
                'value' => 'Daftar Member',
                'type' => 'text',
                'group' => 'Home Page',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'home_cta_secondary_btn_text',
                'display_name' => 'Home CTA Secondary Button Text',
                'value' => 'Pelajari Benefit',
                'type' => 'text',
                'group' => 'Home Page',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Organization Page Config
            [
                'key' => 'org_page_chip',
                'display_name' => 'Organization Page Chip/Badge',
                'value' => 'Portal Informasi KHI',
                'type' => 'text',
                'group' => 'Organization',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'org_page_title',
                'display_name' => 'Organization Page Title',
                'value' => 'Structure, Vision & Heritage',
                'type' => 'text',
                'group' => 'Organization',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'org_page_subtitle',
                'display_name' => 'Organization Page Subtitle',
                'value' => 'Mengenal tata kelola keorganisasian, komitmen pelestarian nilai sejarah, serta lini masa pencapaian luar biasa Komunitas Historia Indonesia sejak tahun 2003.',
                'type' => 'textarea',
                'group' => 'Organization',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'org_page_team_title',
                'display_name' => 'Organization Team Section Title',
                'value' => 'Our Team',
                'type' => 'text',
                'group' => 'Organization',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'org_page_team_subtitle',
                'display_name' => 'Organization Team Section Subtitle',
                'value' => 'Tim kami terdiri dari individu-individu yang penuh semangat, berdedikasi untuk mempromosikan sejarah, budaya, dan nasionalisme Indonesia. Bersama-sama, kami mengorganisir acara, program, dan tur edukatif yang menginspirasi masyarakat untuk lebih mengenal dan mencintai warisan bangsa.',
                'type' => 'textarea',
                'group' => 'Organization',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'org_page_achievements_title',
                'display_name' => 'Organization Achievements Section Title',
                'value' => 'Penghargaan & Prestasi',
                'type' => 'text',
                'group' => 'Organization',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'org_page_achievements_subtitle',
                'display_name' => 'Organization Achievements Section Subtitle',
                'value' => 'Dedikasi KHI mendapat apresiasi tinggi dan pengakuan nasional dari kementerian serta lembaga terkemuka.',
                'type' => 'textarea',
                'group' => 'Organization',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'org_page_milestones_title',
                'display_name' => 'Organization Milestones Section Title',
                'value' => 'Lini Masa Perjalanan KHI',
                'type' => 'text',
                'group' => 'Organization',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'org_page_milestones_subtitle',
                'display_name' => 'Organization Milestones Section Subtitle',
                'value' => 'Menyusuri tonggak-tonggak sejarah pembentukan Komunitas Historia Indonesia.',
                'type' => 'textarea',
                'group' => 'Organization',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'org_page_collab_chip',
                'display_name' => 'Organization Collaboration Section Chip',
                'value' => 'Sponsorship & Partnership',
                'type' => 'text',
                'group' => 'Organization',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'org_page_collab_title',
                'display_name' => 'Organization Collaboration Section Title',
                'value' => 'Kolaborasi Bersama KHI',
                'type' => 'text',
                'group' => 'Organization',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'org_page_collab_subtitle',
                'display_name' => 'Organization Collaboration Section Subtitle',
                'value' => 'Komunitas Historia Indonesia (KHI) membuka kesempatan seluas-luasnya bagi perusahaan, institusi, dan sponsor untuk bermitra dalam melestarikan sejarah, cagar budaya, dan mengedukasi publik. Mari bersama wujudkan sinergi positif demi menjaga memori kolektif bangsa.',
                'type' => 'textarea',
                'group' => 'Organization',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'org_page_collab_contact_title',
                'display_name' => 'Organization Collaboration Contact Section Title',
                'value' => 'Hubungi Tim Kemitraan',
                'type' => 'text',
                'group' => 'Organization',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'org_page_collab_email_label',
                'display_name' => 'Organization Collaboration Email Label',
                'value' => 'Email Resmi',
                'type' => 'text',
                'group' => 'Organization',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'org_page_collab_email',
                'display_name' => 'Organization Collaboration Email Address',
                'value' => 'info@komunitashistoria.com',
                'type' => 'text',
                'group' => 'Organization',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'org_page_collab_phone_label',
                'display_name' => 'Organization Collaboration Phone Label',
                'value' => 'WhatsApp / Telepon',
                'type' => 'text',
                'group' => 'Organization',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'org_page_collab_phone',
                'display_name' => 'Organization Collaboration Phone Number',
                'value' => '+62 818-0807-3636',
                'type' => 'text',
                'group' => 'Organization',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'org_page_collab_btn_text',
                'display_name' => 'Organization Collaboration Button Text',
                'value' => 'Ajukan Penawaran',
                'type' => 'text',
                'group' => 'Organization',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Join Page Config
            [
                'key' => 'join_page_chip',
                'display_name' => 'Join Page Chip/Badge',
                'value' => 'Keanggotaan KHI',
                'type' => 'text',
                'group' => 'Join',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'join_page_title',
                'display_name' => 'Join Page Title',
                'value' => 'Become a Keeper of History',
                'type' => 'text',
                'group' => 'Join',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'join_page_subtitle',
                'display_name' => 'Join Page Subtitle',
                'value' => 'Join a prestigious community dedicated to scholarly preservation and public advocacy. By becoming an official member, you directly fund local heritage restoration campaigns and independent archival expeditions.',
                'type' => 'textarea',
                'group' => 'Join',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'join_page_image',
                'display_name' => 'Join Page Showcase Image',
                'value' => 'https://static.wixstatic.com/media/4dda9f_9ef8c0b1d37349c19b2c061f1f321e2d.jpg/v1/fill/w_1000,h_666,al_c,q_85,usm_0.66_1.00_0.01/4dda9f_9ef8c0b1d37349c19b2c061f1f321e2d.jpg',
                'type' => 'text',
                'group' => 'Join',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'join_page_privileges_title',
                'display_name' => 'Join Page Privileges List Title',
                'value' => 'Eksklusivitas Anggota KHI',
                'type' => 'text',
                'group' => 'Join',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'join_page_privilege_1_title',
                'display_name' => 'Join Privilege 1 Title',
                'value' => 'Exclusive Archives',
                'type' => 'text',
                'group' => 'Join',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'join_page_privilege_1_desc',
                'display_name' => 'Join Privilege 1 Description',
                'value' => 'Full digital access to rare manuscripts and primary source documents.',
                'type' => 'textarea',
                'group' => 'Join',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'join_page_privilege_2_title',
                'display_name' => 'Join Privilege 2 Title',
                'value' => 'Scholarly Journals',
                'type' => 'text',
                'group' => 'Join',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'join_page_privilege_2_desc',
                'display_name' => 'Join Privilege 2 Description',
                'value' => 'Quarterly physical delivery of KHI historical monographs.',
                'type' => 'textarea',
                'group' => 'Join',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'join_page_privilege_3_title',
                'display_name' => 'Join Privilege 3 Title',
                'value' => 'Curated Events',
                'type' => 'text',
                'group' => 'Join',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'join_page_privilege_3_desc',
                'display_name' => 'Join Privilege 3 Description',
                'value' => 'Priority reservation and 20% discount on history tours.',
                'type' => 'textarea',
                'group' => 'Join',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'join_page_privilege_4_title',
                'display_name' => 'Join Privilege 4 Title',
                'value' => 'Voting Rights',
                'type' => 'text',
                'group' => 'Join',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'join_page_privilege_4_desc',
                'display_name' => 'Join Privilege 4 Description',
                'value' => 'Vote on community restoration proposals and board decisions.',
                'type' => 'textarea',
                'group' => 'Join',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'join_page_form_title',
                'display_name' => 'Join Page Form Title',
                'value' => 'Register Today',
                'type' => 'text',
                'group' => 'Join',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'join_page_form_subtitle',
                'display_name' => 'Join Page Form Subtitle',
                'value' => 'Secure your place in the modern archive.',
                'type' => 'textarea',
                'group' => 'Join',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'join_page_form_btn_text',
                'display_name' => 'Join Page Form Submit Button Text',
                'value' => 'Bergabung Sekarang',
                'type' => 'text',
                'group' => 'Join',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'join_page_form_footer',
                'display_name' => 'Join Page Form Footer Text',
                'value' => 'By joining, you agree to our scholarly code of conduct.',
                'type' => 'textarea',
                'group' => 'Join',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Collaboration Page Config
            [
                'key' => 'collab_page_title',
                'display_name' => 'Collaboration Page Title',
                'value' => 'Collaboration',
                'type' => 'text',
                'group' => 'Collaboration',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'collab_page_description',
                'display_name' => 'Collaboration Page Description',
                'value' => 'Temukan kolaborasi yang menarik, ayo berkolaborasi bersama kami!',
                'type' => 'textarea',
                'group' => 'Collaboration',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($settings as $setting) {
            DB::table('settings')->updateOrInsert(
                ['key' => $setting['key']],
                [
                    'display_name' => $setting['display_name'],
                    'value' => $setting['value'],
                    'type' => $setting['type'],
                    'group' => $setting['group'],
                    'created_at' => $setting['created_at'],
                    'updated_at' => $setting['updated_at'],
                ]
            );
        }
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        $keys = [
            'home_events_title',
            'home_events_subtitle',
            'home_events_view_all_text',
            'home_events_register_text',
            'home_library_title',
            'home_library_subtitle',
            'home_library_explore_text',
            'home_library_read_sample_text',
            'home_library_get_ebook_text',
            'home_merchandise_title',
            'home_merchandise_subtitle',
            'home_merchandise_view_all_text',
            'home_merchandise_view_product_text',
            'home_news_title',
            'home_news_subtitle',
            'home_news_view_all_text',
            'home_news_read_more_text',
            'home_recognition_title',
            'home_recognition_subtitle',
            'home_cta_title',
            'home_cta_subtitle',
            'home_cta_primary_btn_text',
            'home_cta_secondary_btn_text',

            'org_page_chip',
            'org_page_title',
            'org_page_subtitle',
            'org_page_team_title',
            'org_page_team_subtitle',
            'org_page_achievements_title',
            'org_page_achievements_subtitle',
            'org_page_milestones_title',
            'org_page_milestones_subtitle',
            'org_page_collab_chip',
            'org_page_collab_title',
            'org_page_collab_subtitle',
            'org_page_collab_contact_title',
            'org_page_collab_email_label',
            'org_page_collab_email',
            'org_page_collab_phone_label',
            'org_page_collab_phone',
            'org_page_collab_btn_text',

            'join_page_chip',
            'join_page_title',
            'join_page_subtitle',
            'join_page_image',
            'join_page_privileges_title',
            'join_page_privilege_1_title',
            'join_page_privilege_1_desc',
            'join_page_privilege_2_title',
            'join_page_privilege_2_desc',
            'join_page_privilege_3_title',
            'join_page_privilege_3_desc',
            'join_page_privilege_4_title',
            'join_page_privilege_4_desc',
            'join_page_form_title',
            'join_page_form_subtitle',
            'join_page_form_btn_text',
            'join_page_form_footer',

            'collab_page_title',
            'collab_page_description',
        ];

        DB::table('settings')->whereIn('key', $keys)->delete();
    }
};
